import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import DashboardLayout from "@/components/DashboardLayout";
import { Suspense } from "react";
import { PlanProvider } from "@/context/PlanContext";

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <PlanProvider>
          <Suspense fallback={<div className="h-screen bg-[#0f172a] text-white flex items-center justify-center">Yükleniyor...</div>}>
            <DashboardLayout>{children}</DashboardLayout>
          </Suspense>
        </PlanProvider>
      </body>
    </html>
  );
}
